apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: krateoctl-install-loadbalancer
  namespace: krateo-system 
spec:
  project: default
  source:
    repoURL: https://github.com/krateoplatformops/releases.git
    targetRevision: 3.0.0-rc2-dev13  # or a specific version
    path: argocd/jobs/loadbalancer  # Choose: nodeport, loadbalancer, or ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: krateo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true  # Important: recreates Job on updates