apiVersion: batch/v1
kind: Job
metadata:
  name: krateoctl-install-ingress
  labels:
    app.kubernetes.io/name: krateoctl-install
    app.kubernetes.io/version: argo-job-testing
    krateo.io/install-type: ingress
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: krateoctl-install
        app.kubernetes.io/version: argo-job-testing
        krateo.io/install-type: ingress
    spec:
      serviceAccountName: krateoctl-install
      restartPolicy: Never
      containers:
        - name: krateoctl
          image: ghcr.io/krateoplatformops/krateoctl:latest
          imagePullPolicy: IfNotPresent
          args:
            - install
            - apply
            - --version
            - "argo-job-testing"
            - --repository
            - "https://github.com/krateoplatformops/releases"
            - --namespace
            - "krateo-system"
            - --type
            - "ingress"
